/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	templatev1 "zeng.dev/kube-template/apis/template/v1"
)

// FakeSamples implements SampleInterface
type FakeSamples struct {
	Fake *FakeTemplateV1
	ns   string
}

var samplesResource = schema.GroupVersionResource{Group: "template", Version: "v1", Resource: "samples"}

var samplesKind = schema.GroupVersionKind{Group: "template", Version: "v1", Kind: "Sample"}

// Get takes name of the sample, and returns the corresponding sample object, and an error if there is any.
func (c *FakeSamples) Get(ctx context.Context, name string, options v1.GetOptions) (result *templatev1.Sample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(samplesResource, c.ns, name), &templatev1.Sample{})

	if obj == nil {
		return nil, err
	}
	return obj.(*templatev1.Sample), err
}

// List takes label and field selectors, and returns the list of Samples that match those selectors.
func (c *FakeSamples) List(ctx context.Context, opts v1.ListOptions) (result *templatev1.SampleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(samplesResource, samplesKind, c.ns, opts), &templatev1.SampleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &templatev1.SampleList{ListMeta: obj.(*templatev1.SampleList).ListMeta}
	for _, item := range obj.(*templatev1.SampleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested samples.
func (c *FakeSamples) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(samplesResource, c.ns, opts))

}

// Create takes the representation of a sample and creates it.  Returns the server's representation of the sample, and an error, if there is any.
func (c *FakeSamples) Create(ctx context.Context, sample *templatev1.Sample, opts v1.CreateOptions) (result *templatev1.Sample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(samplesResource, c.ns, sample), &templatev1.Sample{})

	if obj == nil {
		return nil, err
	}
	return obj.(*templatev1.Sample), err
}

// Update takes the representation of a sample and updates it. Returns the server's representation of the sample, and an error, if there is any.
func (c *FakeSamples) Update(ctx context.Context, sample *templatev1.Sample, opts v1.UpdateOptions) (result *templatev1.Sample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(samplesResource, c.ns, sample), &templatev1.Sample{})

	if obj == nil {
		return nil, err
	}
	return obj.(*templatev1.Sample), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSamples) UpdateStatus(ctx context.Context, sample *templatev1.Sample, opts v1.UpdateOptions) (*templatev1.Sample, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(samplesResource, "status", c.ns, sample), &templatev1.Sample{})

	if obj == nil {
		return nil, err
	}
	return obj.(*templatev1.Sample), err
}

// Delete takes name of the sample and deletes it. Returns an error if one occurs.
func (c *FakeSamples) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(samplesResource, c.ns, name), &templatev1.Sample{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSamples) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(samplesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &templatev1.SampleList{})
	return err
}

// Patch applies the patch and returns the patched sample.
func (c *FakeSamples) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *templatev1.Sample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(samplesResource, c.ns, name, pt, data, subresources...), &templatev1.Sample{})

	if obj == nil {
		return nil, err
	}
	return obj.(*templatev1.Sample), err
}
