# permissions for end users to edit apples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apple-editor-role
rules:
- apiGroups:
  - fruit.zeng.dev
  resources:
  - apples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fruit.zeng.dev
  resources:
  - apples/status
  verbs:
  - get
