---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fruit.zeng.dev
  resources:
  - apples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fruit.zeng.dev
  resources:
  - apples/finalizers
  verbs:
  - update
- apiGroups:
  - fruit.zeng.dev
  resources:
  - apples/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - template.zeng.dev
  resources:
  - samples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - template.zeng.dev
  resources:
  - samples/finalizers
  verbs:
  - update
- apiGroups:
  - template.zeng.dev
  resources:
  - samples/status
  verbs:
  - get
  - patch
  - update
