/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "zeng.dev/kube-template/apis/fruit/v1beta1"
	scheme "zeng.dev/kube-template/client/versioned/scheme"
)

// ApplesGetter has a method to return a AppleInterface.
// A group's client should implement this interface.
type ApplesGetter interface {
	Apples(namespace string) AppleInterface
}

// AppleInterface has methods to work with Apple resources.
type AppleInterface interface {
	Create(ctx context.Context, apple *v1beta1.Apple, opts v1.CreateOptions) (*v1beta1.Apple, error)
	Update(ctx context.Context, apple *v1beta1.Apple, opts v1.UpdateOptions) (*v1beta1.Apple, error)
	UpdateStatus(ctx context.Context, apple *v1beta1.Apple, opts v1.UpdateOptions) (*v1beta1.Apple, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.Apple, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.AppleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Apple, err error)
	AppleExpansion
}

// apples implements AppleInterface
type apples struct {
	client rest.Interface
	ns     string
}

// newApples returns a Apples
func newApples(c *FruitV1beta1Client, namespace string) *apples {
	return &apples{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the apple, and returns the corresponding apple object, and an error if there is any.
func (c *apples) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Apple, err error) {
	result = &v1beta1.Apple{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apples").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Apples that match those selectors.
func (c *apples) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.AppleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.AppleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apples").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested apples.
func (c *apples) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("apples").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a apple and creates it.  Returns the server's representation of the apple, and an error, if there is any.
func (c *apples) Create(ctx context.Context, apple *v1beta1.Apple, opts v1.CreateOptions) (result *v1beta1.Apple, err error) {
	result = &v1beta1.Apple{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("apples").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(apple).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a apple and updates it. Returns the server's representation of the apple, and an error, if there is any.
func (c *apples) Update(ctx context.Context, apple *v1beta1.Apple, opts v1.UpdateOptions) (result *v1beta1.Apple, err error) {
	result = &v1beta1.Apple{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("apples").
		Name(apple.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(apple).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *apples) UpdateStatus(ctx context.Context, apple *v1beta1.Apple, opts v1.UpdateOptions) (result *v1beta1.Apple, err error) {
	result = &v1beta1.Apple{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("apples").
		Name(apple.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(apple).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the apple and deletes it. Returns an error if one occurs.
func (c *apples) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apples").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *apples) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apples").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched apple.
func (c *apples) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Apple, err error) {
	result = &v1beta1.Apple{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("apples").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
